# Generated by Django 2.0.6 on 2018-07-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='serivce_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='service_description',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='service_image', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='service',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
